# Generated by Django 3.1.3 on 2023-02-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230217_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
