# Generated by Django 4.1.6 on 2023-02-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
