# Generated by Django 4.1.2 on 2023-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_item_description_alter_item_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pieces',
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.CharField(blank=True, choices=[('Best Selling Foods', 'Best Selling Foods'), ('New Food', 'New Food'), ('Spicy Foods', 'Spicy Foods')], max_length=25),
        ),
    ]
