# Generated by Django 4.1.2 on 2023-02-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_item_pieces_alter_item_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='status',
        ),
    ]
